spring:
  data:
    mongodb:
      uri: mongodb://${MONGOHOST}:${MONGOPORT}/test
      authentication-database: admin
      username: ${MONGOUSER}
      password: ${MONGOPASSWORD}
      database: ${DATABASE}

