spring:
  data:
    mongodb:
      uri: mongodb://${MONGOHOST}:${MONGOPORT}
      authentication-database: admin
      username: ${MONGOUSER}
      password: ${MONGOPASSWORD}
      database: ${DATABASE}

